server:
  port: 8081
  servlet:
    context-path: /api
    session:
      timeout: 15m

spring:
  application:
    name: spring-demo
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: beans,mappings
      base-path: /actuator
  info:
    env:
      enabled: true

info:
  app:
    name: Spring Demo
    description: Aplicação Spring
    version: 1.0.0

coach:
  name: Mickey Mouse
team:
  name: The Mouse Club

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: TRACE
  file:
    name: my-crazy-stuff.log
    path: c:/myapps/demo